# Generated by Django 3.2.23 on 2024-06-05 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aikidsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='timer',
            field=models.TimeField(default=False),
        ),
    ]
