# Generated by Django 3.2.23 on 2024-06-05 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aikidsapp', '0002_item_timer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='timer',
            field=models.TimeField(),
        ),
    ]
